"""Fail when Python dependency declarations and exported locks diverge."""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BACKEND = ROOT / "apps" / "backend"


def _run_uv(*arguments: str) -> subprocess.CompletedProcess[str]:
    uv = shutil.which("uv")
    if uv is None:
        print(
            "uv is required; install the locked backend test dependencies first.",
            file=sys.stderr,
        )
        raise SystemExit(2)
    return subprocess.run(
        [uv, *arguments],
        cwd=ROOT,
        check=False,
        capture_output=True,
        text=True,
    )


def _without_generated_header(content: str) -> str:
    lines = content.replace("\r\n", "\n").splitlines(keepends=True)
    if lines and lines[0].startswith("# This file was autogenerated by uv"):
        lines = lines[2:]
    return "".join(lines)


def _verify_export(lock_name: str, *, extra: str | None = None) -> bool:
    command = [
        "export",
        "--project",
        "apps/backend",
        "--locked",
        "--format",
        "requirements-txt",
        "--no-emit-project",
        "--no-header",
    ]
    if extra is not None:
        command.extend(["--extra", extra])

    result = _run_uv(*command)
    if result.returncode != 0:
        print(result.stderr, file=sys.stderr, end="")
        return False

    lock_path = BACKEND / lock_name
    expected = _without_generated_header(lock_path.read_text(encoding="utf-8"))
    actual = result.stdout.replace("\r\n", "\n")
    if actual == expected:
        return True

    print(
        f"{lock_path.relative_to(ROOT)} is stale; regenerate all backend locks.",
        file=sys.stderr,
    )
    return False


def main() -> int:
    lock_check = _run_uv("lock", "--project", "apps/backend", "--check")
    if lock_check.returncode != 0:
        print(lock_check.stderr, file=sys.stderr, end="")
        print(
            "apps/backend/uv.lock is stale; run `uv lock --project apps/backend`.",
            file=sys.stderr,
        )
        return 1

    production_current = _verify_export("requirements.lock")
    test_current = _verify_export("requirements-test.lock", extra="test")
    if not production_current or not test_current:
        return 1

    print("Python dependency declarations and all three lock files are synchronized.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
